### ISSUE TITLE
pin_memory=TrueはCPUのみの場合動かない

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/python-dlshogi2#1]
https://github.com/TadaoYamaoka/python-dlshogi2/blob/8c4b8a2c706c29defe7c8e7a23db28474c3c99cf/pydlshogi2/player/mcts_player.py#L170

CPUのみの場合はpin_memory=Trueを削ると動作する。

**Comment by TadaoYamaoka** [comment]
修正しました。ご指摘ありがとうございます。
